refresh-tokens:
  handler: src/auth/main/routes/login/refresh-tokens/function.handler
  layers:
    - ${self:custom.layers.common}
    - ${self:custom.layers.criptography}
    - ${self:custom.layers.typeORM}
  events:
    - http:
        path: refresh
        method: POST