sign-up:
  handler: src/auth/main/routes/login/sign-up/function.handler
  layers:
    - ${self:custom.layers.common}
    - ${self:custom.layers.criptography}
    - ${self:custom.layers.typeORM}
  events:
    - http:
        path: sign-up
        method: POST