login:
  handler: src/auth/main/routes/login/login/function.handler
  layers:
    - ${self:custom.layers.common}
    - ${self:custom.layers.criptography}
    - ${self:custom.layers.typeORM}
  events:
    - http:
        path: login
        method: POST