service: cc-authorizer-api

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-ssm-fetch

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 30
  logRetentionInDays: 60
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions: ${file(src/auth/main/routes/index.yml)}

custom:
  serverlessSsmFetch:    
    DB_HOST: /carb-counting-auth/${self:provider.stage}/DB_HOST
    DB_DATABASE_NAME: /carb-counting-auth/${self:provider.stage}/DB_DATABASE_NAME
    DB_USERNAME: /carb-counting-auth/${self:provider.stage}/DB_USERNAME
    DB_PASSWORD: /carb-counting-auth/${self:provider.stage}/DB_PASSWORD
    JWT_SECRET: /carb-counting-auth/${self:provider.stage}/JWT_SECRET
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: 
      forceInclude:
        - pg