service: cc-layers

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}

layers:
  common:
    path: ./layers/common
  criptography:
    path: ./layers/criptography
  typeorm:
    path: ./layers/typeorm

resources:
  Outputs:
    CommonLayerExport:
      Value:
        Ref: CommonLambdaLayer
      Export:
        Name: CommonLambdaLayer
    CriptographyLayerExport:
      Value:
        Ref: CriptographyLambdaLayer
      Export:
        Name: CriptographyLambdaLayer
    TypeORMLayerExport:
      Value:
        Ref: TypeormLambdaLayer
      Export:
        Name: TypeORMLambdaLayer

custom:
  bundle:
    linting: false