service: cc-meal-api
variablesResolutionMode: 20210326

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 30
  logRetentionInDays: 60
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DB_HOST: ${ssm:/carb-counting-meal/${self:provider.stage}/DB_HOST}
    DB_DATABASE_NAME: ${ssm:/carb-counting-meal/${self:provider.stage}/DB_DATABASE_NAME}
    DB_USERNAME: ${ssm:/carb-counting-meal/${self:provider.stage}/DB_USERNAME}
    DB_PASSWORD: ${ssm:/carb-counting-meal/${self:provider.stage}/DB_PASSWORD}

functions: ${file(src/meal/main/routes/index.yml)}

custom:
  authorizer: ${cf:cc-authorizer-api-${self:provider.stage}.AuthorizerLambdaFunctionQualifiedArn}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: 
      forceInclude:
        - pg