service: cc-authorizer-api

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 30
  logRetentionInDays: 60
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  test:
    handler: src/index.handler
    events:
      - http:
          path: test
          method: POST

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true